version: '3'
services:
  app:
    build: .
    container_name: booksummary-rails
    command: bundle exec rails s -p 3030 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 3030:3030
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    platform: linux/x86_64
    image: mysql:8.0
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
volumes:
  db-volume: